import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Category from '../components/Category'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import TeamSection from '../components/Team'

const Web: NextPage = () => {
  
  return (
   <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
      </Head>
      <Navbar/>
        <HeroSection/>
        <Category/>
        <About/>
        <TeamSection/>
        <Contact/>
      <Footer/>
      
      
</>
  )
}

export default Web
